# Generated by Django 2.2.1 on 2019-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pedidos',
            field=models.ManyToManyField(to='delivery.Pedido'),
        ),
    ]
