# Generated by Django 2.2.1 on 2019-10-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_cliente_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='client_name',
            field=models.CharField(default='patrickctrf', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
